services: 
  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    depends_on:
      - db
  front: 
    build: ./front
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password